talkiq/circleci-orbs

tester/orb.yaml
To make https://github.com/talkiq/tooling/pull/106/files easier in the future.
=> feat(tester): add new cwd arg

gcloud/orb.yaml
- `gcloud/deploy-cloud-run`
- `gcloud/deploy-cloud-function`
- bump version???
- add descriptions for more parameters???
=> feat(gcloud): add deploy-cloud-run and deploy-cloud-function

gcloud/orb.yaml
...including on failure, to help debug https://app.circleci.com/jobs/github/talkiq/tooling/11291
=> feat(gcloud): always print GCR deploy output

deployer/orb.yaml
Long since deprecated and unused, time to release a major version bump.
=> feat(deployer): nuke deprecated docs job

docker/orb.yaml, gcloud/orb.yaml
This seem to work, however some stages failed, I'm gonna investigate if this is related https://app.circleci.com/pipelines/github/talkiq/realtime/1827/workflows/c698fe67-f2f1-459e-9c3e-327f256d44d0/jobs/8739
=> feat(docker): Enable BuildKit

linter/orb.yaml
https://dialpad.slack.com/archives/CB42LKUJ0/p1611790160023500
=> feat(linter) customizable pre-commit version

.circleci/config.yml
=> chore(circleci): Bump circleci/orb-tools

.circleci/config.yml
=> chore(circleci): Remove patch

tester/orb.yaml
Bump the `gcloud` version to the latest major release.
=> chore(tester): Bump gcloud version

docs/orb.yaml
Bump version of `gcloud` in `talkiq/docs`
=> chore(doc): Bump gcloud version

gcloud/orb.yaml
Expect Poetry when deploying GCFs instead of `requirements.txt` files.
=> refactor(gcloud): switch gcf deploy to poetry

gcloud/orb.yaml
This PR unblocks: https://github.com/talkiq/tooling/pull/1753
Not sure if my approach is correct, lmk if there's a better way we should do this.
=> feat(gcloud): make deploy-cloud-function use gcpar

gcloud/orb.yaml
Hotfix for https://dialpad.slack.com/archives/C032J2L17KQ/p1646846366298429
- https://app.circleci.com/pipelines/github/talkiq/realtime-nlp/8006/workflows/a5dc901b-de3e-4ce4-8aba-df743a452917
=> feat(gcloud): allow pinning gcloud cli version

linter/orb.yaml
At some point, this functionality got builtin. Simplify our code!
=> refactor(linter): use builtin show-diff arg

docker/orb.yaml
Adding docker command to push with custom tag (used for building the multiplatform gradle base image)
=> Add new command to docker orb to push image with a custom tag

gcloud/orb.yaml
Seems as though the original issue has been fixed, unpin.
=> feat(gcloud): unpin defualt version

gcloud/orb.yaml
See https://docs.talkiq-echelon.talkiq.com/static/docs/guides/google-auth.html#kubectl-authentication
=> feat(gke): support auth for v1.25+ of gke

gcloud/orb.yaml
See https://dialpad.slack.com/archives/GA91FTLDU/p1673464449394329
=> fix(gcloud): support cloudrun apps without env vars

gcloud/orb.yaml
gsutil -> gcloud storage, for the perf win and to avoid the reliance on an
extra component.
Breaking change!
=> perf(gcloud): replace gsutil with gcloudstorage

gcloud/orb.yaml
Sometimes it doesn't make sense too pass a default project; eg. when
you'll be interacting with multiple projects in a job anyway, or when
you're making use of non-project-specific resources.
=> feat(gcloud): make auth/project param optional

docker/orb.yaml
Confirmed this is indeed no longer necessary.
=> feat(docker): remove unnecessary compose LDPATH workaround

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/autoapproval.yml, .pre-commit-config.yaml
=> chore(repo): bump config from repo-template

gcloud/orb.yaml
Expose version for `docker-configure` to `gcloud/publish` for
`setup_remote_docker`.
=> feat: Allow gcloud/publish to expose setup_remote_docker version

gcloud/orb.yaml
The deprecation date of container registry is fast approaching... this is
necessary to let us migrate over to artifact registry.
=> feat(gcloud): support pushing to artifact registry

.github/renovate.json5
I overhauled my shared renovate configs to make things a bunch more granular
(https://github.com/TheKevJames/tools/commit/0f05ec1246df62f732382648b00ee122fe57b611 ).
This commit migrates our changes in-place to follow the new schema. Should be a
noop!
=> refactor(renovate): clean up renovate config

docker/orb.yaml
Re open this pr https://github.com/talkiq/circleci-orbs/pull/204, based on the comment @TheKevJames did here: https://github.com/talkiq/circleci-orbs/pull/205#pullrequestreview-3043788719
=> call tag-with-latest image only if master or main branch

docker/orb.yaml
The previous conditional wasnt working , it never run , instead of only running on master and main branch
=> fix(docker): tag latest only in master/main branch
