- tester/orb.yaml
This introduces the ability to run `pip check` against your installed
dependencies, to check for any version conflict issues.
> feat(tester): add pip check

- deployer/orb.yaml
Allows for versioning by semver which follows `{major}.{minor}.{patch}-{prerelease}.{version}`
> chore(versions): Allow for alternate versioning

- gcloud/orb.yaml
Looks like `google/cloud-sdk:alpine` has removed `python2` and swapped
in `python3`.
> fix(gcloud): use py3 for gke template deploys

- gcloud/orb.yaml
Otherwise, the values here will be non-deterministic in any cases where
there are multiple deployments to the same zone.
> feat(gcloud): track metadata for individual deployments

- gcloud/orb.yaml
`model-api` is currently experiencing TOOLING-2T, which turns out to
have been stemmed by the fact that our live revision is from January --
new deployments have not actually been getting any traffic.
This changeset ensures that after every deployment we ensure that the
new deployment is the one to which we feed traffic.
See https://dialpad.slack.com/archives/GA91FTLDU/p1587410804037200
> fix(gcloud): fixup cloudrun traffic split on deploy

- deployer/orb.yaml
- docker/orb.yaml
- docs/orb.yaml
- gcloud/orb.yaml
- linter/orb.yaml
- tester/orb.yaml
The goal here is to make things more configurable, eg. so users can run
jobs on larger instances for heftier CI steps. Additionally, this sets
the default to `small` instead of `medium` (ie. the CircleCI default
when unspecified) for cases where a single CPU should generally be
enough.
> feat: allow resource_class configuration

- tester/orb.yaml
Surprisingly for me, docker-compose works pretty seamlessly in circleci.
Green build: https://app.circleci.com/pipelines/github/talkiq/realtime/1883/workflows/a291ae1f-9dc3-4a6e-8cc6-bffad54e307c/jobs/9329
> feat(tester): add job for running docker-compose integration tests

- tester/orb.yaml
Two improvements here:
1. Let client decide which `docker-compose.yaml` files to run. This is needed so we could explicitly only run `-f docker-compose.yaml` and not touch `docker-compose.override.yaml`. 
`docker-compose.override.yaml` -> is a file read by default. Here we can put things that exist for local convenience (primarily volumes with code). https://github.com/talkiq/realtime/pull/408/files#diff-f411261c4abb5a1df0ec1827371502ebR1 This allows us to get rid of CI-specific `integration-tests` service!
2. Output logs if previous step failed
> Improve Tester

- gcloud/orb.yaml
I think this will speed up builds by allowing users to enable docker caching: https://circleci.com/docs/2.0/docker-layer-caching/
> add parameter to enable docker layer caching

- tester/orb.yaml
So we need to pull images from GCR, for this we need to install and setup gcloud, and for that we need to run base `cimg` image under root.
> feat(tester): Let tester fetch images from GCR

- tester/orb.yaml
OK so by default `docker-compose logs` records sorted in the order they were received from containers which isn't really chronological. This PR uses [this workaround](https://github.com/docker/compose/issues/5398#issuecomment-654816131) to properly sort logs.
> chore(tester) Sort docker-compose logs

- gcloud/orb.yaml
I noticed we have this option available but don't expose it to the jobs (i.e. `gcloud/docker-publish`) that use it; therefore it is always set to `false`.
> feat(gcloud): expose docker layer caching to gcloud build

- gcloud/orb.yaml
- tester/orb.yaml
CircleCI is deprecating[1] these older versions in about a month.
1: https://discuss.circleci.com/t/old-linux-machine-image-remote-docker-deprecation/37572
> fix(docker): bump to non-deprecated versions

- gcloud/orb.yaml
Migrate CI steps from my canary work into `circleci-orbs` to make use of it in more repos. Primary differences with the current `gcloud/deploy-gke` job:
- Input k8s YAML instead of generating it within the deploy job
- Job simply pushes k8s YAML to GKE (and still records previous version of deploy)
- Allows for pruning
- Doesn't allow for in-place modification of docker image tag, etc.
The `gcloud/patch-configmap-entry` and `gcloud/force-redeploy-gke` commands can be used in `post-steps` to update the autoscaler.
> feat(gcloud): add k8s-input gke deploy job w/ autoscaler update

- .circleci/config.yml
- README.rst
- poetry/orb.yaml
Creates a new orb "poetry" which can be used to run arbitrary commands via poetry (eg. to run pytest on a package) and to publish the package to the given PyPI respository.
Additionally, significantly simplifies our CircleCI config, as that has been getting more unwieldy with each new orb.
> feat(poetry): create new poetry orb

- gcloud/orb.yaml
This PR adds support for publishing 3rd party images to Google Cloud. Feature added to support publishing projects not compatible by the CircleCI `checkout`
> feat(gcloud): Support publishing containers from third-party vendors

- poetry/orb.yaml
The default `poetry install` output uses a whole bunch of special
ANSI characters which don't play nicely with CircleCI -- it ends up
duplicating each "Installing" line dozens of times.
Stop doing that.
> chore(poetry): disable ANSI output

- poetry/orb.yaml
I think that regardless of our resolution steps to Gemfury `404` issues, we should use the same convention that Gemfury suggests.
> chore(poetry): use gemfury token for username/pass

- linter/orb.yaml
You know when you `git diff` and the output is paged by default which is usually nice? Apparently this causes issues as circle waits to receive the full output, which never arrives and we end up timing out after 10 minutes. For instance, see this [failed job](https://app.circleci.com/pipelines/github/talkiq/realtime-decoder/5752/workflows/f44b95af-1efc-4556-b1d7-304fc128a293/jobs/47918).
> fix(linter): paged output can cause long timeouts

- gcloud/orb.yaml
This PR adds support for publishing packages to GCP's Artifact Registry [Python] Package Repository.
> feat(gcloud): Support publishing packages to GCP Artifact Registry

- gcloud/orb.yaml
When publishing twice, `install` causes errors because Google SDK already installed
> bug(gcloud): Prevent double-install error

- docker/orb.yaml
- gcloud/orb.yaml
- tester/orb.yaml
How it started: https://dialpad.slack.com/archives/GA91FTLDU/p1623882936426100
How it's going: https://dialpad.slack.com/archives/GA91FTLDU/p1623889383442900
Tested on tooling: https://app.circleci.com/pipelines/github/talkiq/tooling/9734/workflows/0d2e7bf0-321d-4a25-ac3f-a0623b50e177
Let me know which repos you think might be at risk and worth testing
> chore: bump remote docker version to 20.10.6

- notifier/orb.yaml
Apparently, there's now an api.datadoghq.eu for folks in the EU. May as
well broaden this up to support that override if anyone external needs
it.
> feat(notifier): support custom datadog domains

- gcloud/orb.yaml
The default value doesn't change anything from current use, but
providing `latest` or a specific version string allows users to specify
the `kubectl` version they need.
> feat(gcloud): allow users to specify kubectl version

- gcloud/orb.yaml
Looks like `kubectl` needs to be linked in the same way as `gcloud` needs to be linked. This wasn't apparent before but since `kubectl client --version` was added as a step recently (https://github.com/talkiq/circleci-orbs/pull/52) this showed up in our CI failures (and I was able to reproduce the behaviour locally within an isolated docker environment).
```
#!/bin/bash -eo pipefail
kubectl version --client
/bin/bash: kubectl: command not found
Exited with code exit status 127
CircleCI received exit code 127
```
> fix(gcloud): link kubectl cli tool

- poetry/orb.yaml
The URL to upload to GCP/Azure private PyPI solutions requires a URL that differs from the download URL. This PR adds passing a `repository-url` to the job to support these "upload-only" URLs.
We could add the upload-only URL to poetry's `pyproject.toml`, but then we rely on poetry to always throw an error and handle it correctly (something that poetry has not always done correctly).
> feat(poetry): Support upload only URLs

- poetry/orb.yaml
https://github.com/talkiq/circleci-orbs/pull/56 as-is will break all our builds because `repository-url` is declared as being required. This change gives `repository-url` a falsey default, thereby making the parameter non-required.
> bug(poetry): Set repository-url as being not required

- poetry/orb.yaml
Extend `run` to support non-Gemfury package repositories. This is a breaking change requiring a major release.
> feat(poetry): Extend run to support non-Gemfury package repositories

- gcloud/orb.yaml
Enable `gcloud/install` to be called multiple times without error. This is change will be published as a patch since it should result in a no-op, unless (!!) a caller of this code used a `when` statement with `on_failure`. I have not found `when` and `gcloud/install` used in this manner.
> feat(gcloud): Support calling install command multiple times

- .circleci/config.yml
Unable to promote `talkiq/tester` to production after upgrading to `orb-tools@8`. Reverting change before further troubleshooting.
> chore(cirlceci): Revert orb-tools version due to publish failure

- .github/renovate.json
Enable updating the orbs via extending supported file types.
We must specify `circleci` as the manager because `orb` is a datasource, not a manager. See https://docs.renovatebot.com/modules/manager/circleci/.
> chore(renovate): Enable updating renovate orbs

- tester/orb.yaml
Support passing arguments to `docker-compose build` such as `--build-args`.
> feat(tester): Add build arguments to docker-compose build

- gcloud/orb.yaml
Unset default memory on GCF deploy and upload from file path. These settings have interfered with required settings in Terraform (which is required for VPC connector, PubSub triggers) and caused the source of truth for GCFs to be split across more than one repo. This change addresses that by making the deploy operation simpler and change nothing about the GCF config.
---
One thing I don't like about this proposal is that this only accounts for memory as being the point of possible discrepancies between TF & CI. What if there are other parameters that come along that we add? Will this hidden dependency hit us again?
What if instead we have a "trigger-only" mode that explicitly does not update any of the other parameters? That would make it abundantly clear that it won't modify your …
> refactor(gcloud): gcf deploy from path & no default mem

- tester/orb.yaml
CircleCI has decided to update the `cimg/base:stable-20.04` image with Docker Compose V2, which now is referenced by `docker compose` instead of `docker-compose`. This has broken our builds since we expected a "stable" image to remain stable. To maintain stability in `talkiq/tester` I am pinning the default executor to the latest compatible version (i.e. last month's image, which uses Docker Compose V1) and releasing a patch version of `talkiq/tester`. I will subsequently release a major version of `talkiq/tester` with references to Docker Compose as `docker compose` and the default executor as `cimg/base:stable-20.04`. This should fix any broken builds and allow users to upgrade to Docker Compose V2 at their leisure.
https://discuss.circleci.com/t/docker-compose-v2-now-in-cimg-base/42184 …
> chore(tester): pin default executor to docker-compose v1

- tester/orb.yaml
As a follow-up to https://github.com/talkiq/circleci-orbs/pull/75, we need to un-pin the `cimg/base` and use the `stable-*` image tag which uses Docker Compose V2 and an incompatible syntax: `s/docker-compose/docker compose/`. I believe that this warrants a release of a major version of `talkiq/tester` in order to keep up to date with `cimg/base` releases as well as having consistent default images that align with how we execute Docker Compose in our orb. I haven't checked yet whether the orb code itself should change but Compose V2 is supposed to be compatible with how V1 is used:
https://docs.docker.com/compose/cli-command/
Thoughts?
> chore(tester): use docker compose v2 in stable cimg container

- .github/CODEOWNERS
- .github/PULL_REQUEST_TEMPLATE.md
As decided in our previous retro, update our CODEOWNERS file to include more explicit ownership on PRs. I've started by tossing in my own stuff (handling renovate PRs), but it would be great to get everyone to add themselves as appropriate to get us "caught up". Note I've also updated the PR template in `docs` to remind us to keep this up-to-date: if folks approve that change, I'll mirror it to this PR.
> chore(github): update CODEOWNERS

- poetry/orb.yaml
managed to invert the syntax for the when branch here: https://github.com/talkiq/circleci-orbs/pull/78
tested this with a dev version
> fixed incorrect job syntax

- notifier/orb.yaml
I added a step inside the command `slack-on-fail` to install `curl`. We need it because otherwise, we will not send slack notifications when `curl` is not installed.
> fix(ci_notification): adding curl installation before sending slack notification

- docs/orb.yaml
- linter/orb.yaml
- tester/orb.yaml
This feels like the only "reasonable" default; previously we've had some
scattered defaults, mostly in the py3.7.x range, but any cases where
users do not want the most up-to-date base image should probably be
places where the user specifies that version anyway.
Breaking change to the relevant orbs as we're changing a default.
> feat(docs,linter,tester): use python:latest be default

- poetry/orb.yaml
Part of the myriad and ongoing efforts to move away from installing poetry via
pip. Also exposes a `poetry/install` command which may be of use elsewhere
downstream.
- @allandialpad this might be useful to you for your realtime-dev PR
> fix(poetry): install poetry via curl

- poetry/orb.yaml
This allows users to override the entire executor, rather than just the
python version and the resource class. By allowing this option, users
should be able to have more customization options such as attaching
environment variables to their image, running background images for
testing purposes, etc.
Note that this is a breaking change!
- https://github.com/talkiq/realtime-decoder/commit/da53b389749a77d95598d724c53b2853375ec20a
> feat(poetry): allow executor overrides

- notifier/orb.yaml
So apparently the Slack "keywords that notify you" only *highlights* the
matching phrase if it does not start with an @ symbol. If we attach the
@ here, then any users who've added their Github username to their Slack
keywords list will correctly get a notification through this orb.
Note that adding the @ here makes this match the deployment failure notifier,
which has been pinging folks correctly.
> feat(notifier): enable slack notifs for deployments

- gcloud/orb.yaml
Give some human-readable names for complex commands that are
incomprehensible in the CI job output pages.
ie. this:
> feat(gcloud): cleaner command names

- deployer/orb.yaml
- docker/orb.yaml
- docs/orb.yaml
- gcloud/orb.yaml
- linter/orb.yaml
- notifier/orb.yaml
#86 was incredibly useful for allowing us to override executors rather than
copy-pasting a bunch of jobs. Executors are also supported by Renovate, which
means we caught some accidental usages of outdated images.
Apply those changes to everything!
* deployer, docker, docs, gcloud, linter: make the above change. BREAKING.
* notifier: make the above change. Not breaking.
* gcloud: additionally allow the docker server version to be specified.
> feat: allow executor overrides in all orbs

- notifier/orb.yaml
Fixup a typo which breaks the notifier orb.
> fix(notifier): fix typo in executor name

- linter/orb.yaml
Plumbs through to the command. No reason to only allow users this option
in one case but not the other!
> feat(linter): expose cache_prefix in job

- gcloud/orb.yaml
Our GCF deploy steps have been failing on Poetry installation which is due to Poetry requiring GCC and other headers (ex. Python dev headers).
> fix(gcloud): deploy fn needs more deps for poetry

- linter/orb.yaml
- Making it possible to change args passed to `pre-commit` (default stays the same, `--all-files --show-diff-on-failure`)
- Add a `setup` parameter that can be used to provide steps ran before the `pre-commit` command runs
> feat(linter): Add optional setup steps + ability to override pre-commit args

- gcloud/orb.yaml
Expose additional `flags` for `gcloud/deploy-cloud-function` and remove the `memory` parameter, which will result in a major version bump on the `gcloud` orb. For more details, please see https://github.com/talkiq/terraform/pull/1867.
> feat(gcloud): add optional flags to gcf deploy

- gcloud/orb.yaml
It seems that on certain versions of linux `apk add curl` is installing a mismatched version of curl and libcurl:
```
82d3cd0591f4:~/project# curl -o foo.bar google.com
curl: (48) An unknown option was passed in to libcurl
```
Eg:
```
a796ad7cecbc:~/project# curl -V
curl 7.87.0 (x86_64-alpine-linux-musl) libcurl/7.86.0 OpenSSL/3.0.7 zlib/1.2.13 brotli/1.0.9 nghttp2/1.51.0
Release-Date: 2022-12-21
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL threadsafe TLS-SRP UnixSockets
WARNING: curl and libcurl versions do not match. Functionality may be affected.
```
and two libcurls get installed side by side:
``` …
```
> Fix "unknown option was passed in to libcurl"

- notifier/orb.yaml
Issues can arise where `apt-get update` fails and then the whole process of trying to notify slack results in failed CI jobs.  Allow the chance for users to install curl on their own and skip package management of any kind.
> Skips curl installation when already present

- linter/orb.yaml
pre-commit only support py3, we should ensure we're running via the
correct python in cases where python2 is also installed, the symlink
doesn't exist, or the symlink points to py2.
> fix(linter): force py3 usage for pre-commit

- gcloud/orb.yaml
For GKE deployments which are deployed to different clusters within the same workflow, referring to `prev_version` in a subsequent workflow step fails due to contention and overwrites. To resolve this we should namespace by cluster when storing the previous GKE deployment version.
> feat(gcloud): namespace prev_version by cluster on deploy

- linter/orb.yaml
BREAKING CHANGE!
With PEP668, global package installations are no longer possible, even
in something like docker where an additional layer of virtualenvs is
entirely meaningless. As such, we need to overhaul this orb to install
pre-commit in a venv, which in turn means alpine-based executors need
shell/env overrides and a single command for "install and run
pre-commit" is not really doable anymore: there are too many different
possible base images to account for them all.
Definitely open to any suggestions, especially on:
* ways to make this less breaking
* any new convenience commands/jobs/etc which would help out here
> fix(linter): support PEP668

- docker/orb.yaml
- gcloud/orb.yaml
See https://discuss.circleci.com/t/remote-docker-image-deprecations-and-eol-for-2024/50176
> chore(ci): bump to non-deprecated docker

- docker/orb.yaml
- gcloud/orb.yaml
Setting docker version to `default` or `current` to make the orb more general. In case we need a specific docker version, we can select it using job parameters.
I don't know how to test this jobs, please, review it carefully
> unpinning docker versions

- README.rst
Clarify how to work with dev versions in this repo.
> docs: clarify usage of dev versions

- poetry/orb.yaml
Allows users to specify the build timeout for processes that take longer than CircleCI's default of 10 minutes.
> chore(poetry-publish): Allow users to specify timeout for poetry build

- .github/CODEOWNERS
> chore: Update CODEOWNERS with cphoward

- gcloud/orb.yaml
This plugin will soon no longer be installed by default, add it
explicitly where we need it.
> fix(poetry): install export plugin
